project:
  type: website

website:
  title: "Joe Fernander"
  site-url: https://joefernander.com
  open-graph:
    locale: en_US
  comments:
    utterances:
      repo: joefernander/resume
  navbar:
    right:
      - text: "Home"
        href: index.html
  page-footer: Website based on template by Mike Mahoney. Made with <i class="fa-brands fa-r-project"></i> and Quarto<br>
format:
  html:
    theme: [cosmo]
    css: styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">