project:
  type: website

website:
  title: "Joe Fernander"
  site-url: https://joefernander.com
  open-graph:
    locale: en_US
  comments:
    utterances:
      repo: joefernander/resume
  navbar:
    right:
      - text: "Home"
        href: index.html
  page-footer:
    center: Website based on template by Mike Mahoney. Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
format:
  html:
    theme: [cosmo]
    css: styles.css
filters:
  - fontawesome