project:
  type: website

website:
  title: "Joe Fernander"
  site-url: https://joefernander.com
  open-graph:
    locale: en_US
  comments:
    utterances:
      repo: joefernander/resume
  navbar:
    right:
      - text: "Home"
        href: index.html
  page-footer:
    left: "Based on Template by Mike Mahoney"
format:
  html:
    theme: [cosmo]
    css: styles.css